project_id = "eebphowrbarzawwixqcc"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = false

[functions.chat-with-ai]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.update-webhook-url]
verify_jwt = true

[functions.test-webhook]
verify_jwt = true

[functions.send-building-data]
verify_jwt = true

[functions.process-bulk-upload]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.query-documents]
verify_jwt = true

[functions.continue-processing]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = true

[functions.classify-document-pages]
verify_jwt = true

[functions.run-agent-search]
verify_jwt = false

[functions.orchestrate-reorganization]
verify_jwt = true
