project_id = "eebphowrbarzawwixqcc"

[functions.admin-create-user]
verify_jwt = true

[functions.chat-with-ai]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.update-webhook-url]
verify_jwt = true

[functions.test-webhook]
verify_jwt = true