-- Migrate IBAN/SEPA data from onboarding_progress to contact_bank_accounts (Neuer Weg 8)

-- 1. Update existing Gayer-Lesti entry
UPDATE public.contact_bank_accounts
SET iban = 'DE04733223802240145890',
    account_holder = 'florian gayer-lesti',
    sepa_mandate_date = '2026-05-15',
    updated_at = now()
WHERE id = '662713e2-91c2-4dd6-9a5c-3595f4ead56e';

-- 2. Insert new entries for the other 4 owners (sepa_mandate_ref auto-generated by trigger)
INSERT INTO public.contact_bank_accounts (contact_id, account_holder, iban, sepa_mandate_date, is_default)
VALUES
  ('ddf60a58-049f-439a-b4d2-c43eba0cc4dd', 'Thomas Hauber', 'DE39600100700334611703', '2026-05-16', true),
  ('524de611-f509-4668-ba11-e086f3bb8db8', 'Frank Weyand', 'DE40594500101010430658', '2026-05-06', true),
  ('02c95d86-535d-4d00-b381-a1f49dca2405', 'Dr. Daniel Junk', 'DE10640500000000795030', '2026-05-17', true),
  ('26433d39-ca8f-48ba-b571-f4a69cc230e6', 'Christiane Grimm', 'DE82870700240294181300', '2026-05-11', true);