UPDATE public.chart_of_accounts SET account_name='Straßenreinigung' WHERE account_number='1000';
UPDATE public.chart_of_accounts SET account_name='Müllabfuhr / Restmüll / Grundgebühren' WHERE account_number='1010';
UPDATE public.chart_of_accounts SET account_name='Papiertonne' WHERE account_number='1011';
UPDATE public.chart_of_accounts SET account_name='Gewerbemüll' WHERE account_number='1013';
UPDATE public.chart_of_accounts SET account_name='Wasserversorgung' WHERE account_number='1030';
UPDATE public.chart_of_accounts SET account_name='Abwasser / Kanal' WHERE account_number='1040';
UPDATE public.chart_of_accounts SET account_name='Allgemeinstrom' WHERE account_number='1050';
UPDATE public.chart_of_accounts SET account_name='Hausmeister' WHERE account_number='1060';
UPDATE public.chart_of_accounts SET account_name='Winterdienst' WHERE account_number='1061';
UPDATE public.chart_of_accounts SET account_name='Hausreinigung' WHERE account_number='1070';
UPDATE public.chart_of_accounts SET account_name='Gartenpflege' WHERE account_number='1080';
UPDATE public.chart_of_accounts SET account_name='Ungezieferbekämpfung' WHERE account_number='1090';
UPDATE public.chart_of_accounts SET account_name='Wartung' WHERE account_number='1100';
UPDATE public.chart_of_accounts SET account_name='Wartung Feuerlöscher' WHERE account_number='1101';
UPDATE public.chart_of_accounts SET account_name='Wartung Rauchwarnmelder' WHERE account_number='1102';
UPDATE public.chart_of_accounts SET account_name='Aufzugskosten Wartung' WHERE account_number='1103';
UPDATE public.chart_of_accounts SET account_name='Aufzugskosten Notruf' WHERE account_number='1104';
UPDATE public.chart_of_accounts SET account_name='Verbrauchsmaterial (Streugut, Grüngut, Kleinmaterial)' WHERE account_number='1110';
UPDATE public.chart_of_accounts SET account_name='Kabelgebühren' WHERE account_number='1120';
UPDATE public.chart_of_accounts SET account_name='Dachrinnenreinigung' WHERE account_number='1130';
UPDATE public.chart_of_accounts SET account_name='Grundsteuer' WHERE account_number='1200';
UPDATE public.chart_of_accounts SET account_name='Versicherungen (Hauptkonto / Sonstige)' WHERE account_number='1300';
UPDATE public.chart_of_accounts SET account_name='Gebäudeversicherung' WHERE account_number='1301';
UPDATE public.chart_of_accounts SET account_name='Sach- und Haftpflichtversicherung' WHERE account_number='1302';
UPDATE public.chart_of_accounts SET account_name='Gewässerschadenversicherung' WHERE account_number='1303';
UPDATE public.chart_of_accounts SET account_name='Heizung / Warmwasser' WHERE account_number='1400';
UPDATE public.chart_of_accounts SET account_name='Brennstoffkauf' WHERE account_number='1410';
UPDATE public.chart_of_accounts SET account_name='Kaminkehrer' WHERE account_number='1420';
UPDATE public.chart_of_accounts SET account_name='Heizung Nebenkosten' WHERE account_number='1430';
UPDATE public.chart_of_accounts SET account_name='Gerätemiete / Zählermiete' WHERE account_number='1431';
UPDATE public.chart_of_accounts SET account_name='Heizung Wartung' WHERE account_number='1440';
UPDATE public.chart_of_accounts SET account_name='Brennstoffrestbestand' WHERE account_number='1450';
UPDATE public.chart_of_accounts SET account_name='CO2-Umlage' WHERE account_number='1460';
UPDATE public.chart_of_accounts SET account_name='CO2-Umlage (Anteil Vermieter)' WHERE account_number='1461';
UPDATE public.chart_of_accounts SET account_name='Verwaltervergütung (Hauptgebäude)' WHERE account_number='1500';
UPDATE public.chart_of_accounts SET account_name='Verwaltervergütung TG' WHERE account_number='1501';
UPDATE public.chart_of_accounts SET account_name='Außerordentliche Verwaltungskosten' WHERE account_number='1502';
UPDATE public.chart_of_accounts SET account_name='Verwaltervergütung Miete / SEV' WHERE account_number='1503';
UPDATE public.chart_of_accounts SET account_name='Porto / Telefon / Bürobedarf' WHERE account_number='1510';
UPDATE public.chart_of_accounts SET account_name='Kontogebühren' WHERE account_number='1520';
UPDATE public.chart_of_accounts SET account_name='Rechts- und Beratungskosten' WHERE account_number='1530';
UPDATE public.chart_of_accounts SET account_name='Mahngebühren' WHERE account_number='1540';
UPDATE public.chart_of_accounts SET account_name='Lohnnebenkosten' WHERE account_number='1580';
UPDATE public.chart_of_accounts SET account_name='Steuer / Berufsgenossenschaft' WHERE account_number='1581';
UPDATE public.chart_of_accounts SET account_name='Laufende Instandhaltung / Reparaturen' WHERE account_number='1600';
UPDATE public.chart_of_accounts SET account_name='Besondere Instandhaltung / Großprojekte' WHERE account_number='1601';
UPDATE public.chart_of_accounts SET account_name='Kleinreparaturen' WHERE account_number='1602';
UPDATE public.chart_of_accounts SET account_name='Mieterwechselkosten / Schönheitsreparaturen' WHERE account_number='1603';
UPDATE public.chart_of_accounts SET account_name='Handwerkerlöhne / Dienste lt. §35a EStG' WHERE account_number='1610';
UPDATE public.chart_of_accounts SET account_name='Summe I. Bewirtschaftungskosten' WHERE account_number='1700';
UPDATE public.chart_of_accounts SET account_name='II. Beitragsverpflichtung IHR' WHERE account_number='1710';
UPDATE public.chart_of_accounts SET account_name='Summe II. Beitrag IHR' WHERE account_number='1730';
UPDATE public.chart_of_accounts SET account_name='III. Einnahmen der WEG' WHERE account_number='1740';
UPDATE public.chart_of_accounts SET account_name='Summe III. Einnahmen' WHERE account_number='1770';
UPDATE public.chart_of_accounts SET account_name='Altschulden aus Abrechnung' WHERE account_number='1780';
UPDATE public.chart_of_accounts SET account_name='Laufendes Bankkonto' WHERE account_number='1800';
UPDATE public.chart_of_accounts SET account_name='Rücklagenkonto' WHERE account_number='1810';
UPDATE public.chart_of_accounts SET account_name='Zinseinnahmen' WHERE account_number='1840';
UPDATE public.chart_of_accounts SET account_name='Kapitalertragssteuer' WHERE account_number='1850';
UPDATE public.chart_of_accounts SET account_name='Solidaritätszuschlag' WHERE account_number='1860';
UPDATE public.chart_of_accounts SET account_name='--- Mitteilungskonten ---' WHERE account_number='1900';
UPDATE public.chart_of_accounts SET account_name='Stand der Rücklage' WHERE account_number='1910';
UPDATE public.chart_of_accounts SET account_name='Reparaturen aus Entnahme Rücklage' WHERE account_number='1920';
UPDATE public.chart_of_accounts SET account_name='Planmäßige IHR Wohnungen' WHERE account_number='1930';
UPDATE public.chart_of_accounts SET account_name='Eröffnungsbuchungen' WHERE account_number='4000';
UPDATE public.chart_of_accounts SET account_name='Irrläufer-Konto / Prüfen' WHERE account_number='4010';
UPDATE public.chart_of_accounts SET account_name='WEG-Abrechnung Sollstellung' WHERE account_number='4020';
UPDATE public.chart_of_accounts SET account_name='Ausgleich NK-Jahresabrechnung' WHERE account_number='4021';
UPDATE public.chart_of_accounts SET account_name='Mietausfallwagnis / Leerstandsverlust' WHERE account_number='4025';
UPDATE public.chart_of_accounts SET account_name='Durchlaufkonto' WHERE account_number='4030';
UPDATE public.chart_of_accounts SET account_name='Ausweis für §35a EStG' WHERE account_number='4040';
UPDATE public.chart_of_accounts SET account_name='--- Abgrenzung ---' WHERE account_number='4100';
UPDATE public.chart_of_accounts SET account_name='Ausgaben im lfd. Jahr für Vorjahr' WHERE account_number='4110';
UPDATE public.chart_of_accounts SET account_name='Ausgaben im lfd. Jahr für Folgejahr' WHERE account_number='4120';
UPDATE public.chart_of_accounts SET account_name='Einnahmen im lfd. Jahr für Vorjahr' WHERE account_number='4130';
UPDATE public.chart_of_accounts SET account_name='Einnahmen im lfd. Jahr für Folgejahr' WHERE account_number='4140';
UPDATE public.chart_of_accounts SET account_name='Ausgaben im Vorjahr für lfd. Jahr' WHERE account_number='4150';
UPDATE public.chart_of_accounts SET account_name='Ausgaben im Folgejahr für lfd. Jahr' WHERE account_number='4160';
UPDATE public.chart_of_accounts SET account_name='Einnahmen im Vorjahr für lfd. Jahr' WHERE account_number='4170';
UPDATE public.chart_of_accounts SET account_name='Einnahmen im Folgejahr für lfd. Jahr' WHERE account_number='4180';
UPDATE public.chart_of_accounts SET account_name='§35a Abs. 2 Satz 1 EStG Mieterbescheinigung' WHERE account_number='7100';
UPDATE public.chart_of_accounts SET account_name='§35a Abs. 3 Satz 1 EStG Mieterbescheinigung' WHERE account_number='7120';
UPDATE public.chart_of_accounts SET account_name='--- NK-Einnahmen ---' WHERE account_number='9000';